spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    show-sql: true
  sql:
    init:
      mode: never

  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
server:
  port: 8080

